config/routes.rb
Rails.application.routes.draw do
  get 'home', to: 'home#index'

  root 'home#index'
  resources :departments
  resources :company_images
  resources :images
  resources :companies
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/company.rb
class Company < ApplicationRecord
  has_many :company_images, dependent: :destroy, inverse_of: :company
  validates_presence_of :name

  accepts_nested_attributes_for :company_images, allow_destroy: true

end

app/models/company_image.rb
class CompanyImage < ApplicationRecord
  belongs_to :company, inverse_of: :company_images
  mount_uploader :logo, ImageUploader
end

app/models/department.rb
class Department < ApplicationRecord
  mount_uploaders :images, ImageUploader
  validates_presence_of :name
end

app/models/image.rb
class Image < ApplicationRecord
  mount_uploader :filename, ImageUploader
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/companies_controller.rb
class CompaniesController < ApplicationController
  before_action :set_company, only: [:show, :edit, :update, :destroy]

  # GET /companies
  # GET /companies.json
  def index
    @companies = Company.all
  end

  # GET /companies/1
  # GET /companies/1.json
  def show
  end

  # GET /companies/new
  def new
    @company = Company.new
    @company.company_images.build
  end

  # GET /companies/1/edit
  def edit
    @company.company_images.build
  end

  # POST /companies
  # POST /companies.json
  def create
    @company = Company.new(company_params)
    respond_to do |format|
      if @company.save
        format.html { redirect_to @company, notice: 'Company was successfully created.' }
        format.json { render :show, status: :created, location: @company }
      else
        @company.company_images.build if company_params['company_images_attributes'].nil?
        format.html { render :new }
        format.json { render json: @company.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /companies/1
  # PATCH/PUT /companies/1.json
  def update
    respond_to do |format|
      if @company.update(company_params)
        format.html { redirect_to @company, notice: 'Company was successfully updated.' }
        format.json { render :show, status: :ok, location: @company }
      else
        format.html { render :edit }
        format.json { render json: @company.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /companies/1
  # DELETE /companies/1.json
  def destroy
    @company.destroy
    respond_to do |format|
      format.html { redirect_to companies_url, notice: 'Company was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_company
      @company = Company.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def company_params
      params.require(:company).permit(:name, company_images_attributes: [:id, :logo, :_destroy, :small_logo])
    end
end

app/controllers/departments_controller.rb
class DepartmentsController < ApplicationController
  before_action :set_department, only: [:show, :edit, :update, :destroy]

  # GET /departments
  # GET /departments.json
  def index
    @departments = Department.all
  end

  # GET /departments/1
  # GET /departments/1.json
  def show
  end

  # GET /departments/new
  def new
    @department = Department.new
  end

  # GET /departments/1/edit
  def edit
  end

  # POST /departments
  # POST /departments.json
  def create
    @department = Department.new(department_params)

    respond_to do |format|
      if @department.save
        format.html { redirect_to @department, notice: 'Department was successfully created.' }
        format.json { render :show, status: :created, location: @department }
      else
        format.html { render :new }
        format.json { render json: @department.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /departments/1
  # PATCH/PUT /departments/1.json
  def update
    respond_to do |format|
      if @department.update(department_params)
        format.html { redirect_to @department, notice: 'Department was successfully updated.' }
        format.json { render :show, status: :ok, location: @department }
      else
        format.html { render :edit }
        format.json { render json: @department.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /departments/1
  # DELETE /departments/1.json
  def destroy
    @department.destroy
    respond_to do |format|
      format.html { redirect_to departments_url, notice: 'Department was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_department
      @department = Department.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def department_params
      params.require(:department).permit(:name, {images: []})
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/images_controller.rb
class ImagesController < ApplicationController
  before_action :set_image, only: [:show, :edit, :update, :destroy]

  # GET /images
  # GET /images.json
  def index
    @images = Image.all
  end

  # GET /images/1
  # GET /images/1.json
  def show
  end

  # GET /images/new
  def new
    @image = Image.new
  end

  # GET /images/1/edit
  def edit
  end

  # POST /images
  # POST /images.json
  def create
    @image = Image.new(image_params)

    respond_to do |format|
      if @image.save
        format.html { redirect_to @image, notice: 'Image was successfully created.' }
        format.json { render :show, status: :created, location: @image }
      else
        format.html { render :new }
        format.json { render json: @image.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /images/1
  # PATCH/PUT /images/1.json
  def update
    respond_to do |format|
      if @image.update(image_params)
        format.html { redirect_to @image, notice: 'Image was successfully updated.' }
        format.json { render :show, status: :ok, location: @image }
      else
        format.html { render :edit }
        format.json { render json: @image.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /images/1
  # DELETE /images/1.json
  def destroy
    @image.destroy
    respond_to do |format|
      format.html { redirect_to images_url, notice: 'Image was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_image
      @image = Image.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def image_params
      params.require(:image).permit(:filename)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/images_helper.rb
module ImagesHelper
end

app/views/companies/_form.html.erb
<%= form_with model: company, local: true, html: { multipart: true } do |form| %>
  <% if company.errors.any? %>
    <div class="alert alert-danger" role="alert">
      <p><%= pluralize(company.errors.count, "error") %> prohibited this company from being saved:</p>
      <ul>
        <% company.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.fields_for :company_images do |ff| %>
      <%= ff.hidden_field :id %>
      <% if ff.object.new_record? %>
        <%= ff.label 'Logo (optional)' %>
        <%= ff.file_field :logo %>
        <p>
          <small>Recommended image size is 132px x 83px. Accepted file types are JPG, JPEG, & PNG.</small>
        </p>
        <%= ff.label 'Small logo?' %>
        <%= ff.check_box :small_logo %>
        <hr />
      <% elsif ff.object.logo.url.present?%>
        <%= image_tag(ff.object.logo.url) %>
        <%= ff.label 'Delete logo' %>
        <%= ff.check_box :_destroy %>
        <hr />
      <% end %>
    <% end %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/companies/edit.html.erb
<%= link_to 'Show', @company, class: 'btn btn-outline-dark m-2' %> |
<%= link_to 'Back', companies_path, class: 'btn btn-outline-secondary m-2' %>

<h1>Editing Company</h1>

<%= render 'form', company: @company %>

app/views/companies/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Companies</h1>
<%= link_to 'New Company', new_company_path, class: 'btn btn-outline-info m-2' %>

<table class="table">
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @companies.each do |company| %>
      <tr>
        <td><%= company.name %></td>
        <td class="d-flex justify-content-end">
          <%= link_to 'Show', company, class: 'btn btn-outline-dark m-2' %>
          <%= link_to 'Edit', edit_company_path(company), class: 'btn btn-outline-warning m-2' %>
          <%= link_to 'Destroy', company, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-outline-danger m-2' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/companies/new.html.erb
<%= link_to 'Back', companies_path, class: 'btn btn-outline-secondary m-2' %>

<h1>New Company</h1>

<%= render 'form', company: @company %>

app/views/companies/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_company_path(@company), class: 'btn btn-outline-warning m-2' %> |
<%= link_to 'Back', companies_path, class: 'btn btn-outline-secondary m-2' %>
<p>
  <strong>Name:</strong>
  <%= @company.name %>
</p>

  <% @company.company_images.each do |company_image | %>
    <% if company_image.logo.url.present? %>
      <%= image_tag (company_image.logo.url) %>
      <p>
        <strong>Small Logo: </strong>
        <%= company_image.small_logo? %>
      </p>
    <% end %>
  <% end %>

app/views/departments/_form.html.erb
<%= form_with(model: department, local: true) do |form| %>
  <% if department.errors.any? %>
  <div class="alert alert-danger" role="alert">
    <p><%= pluralize(department.errors.count, "error") %> prohibited this department from being saved:</p>
    <ul>
      <% department.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>
  <div class="field">
    <%= form.file_field :images, multiple: true %>
  </div>
  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/departments/edit.html.erb
<%= link_to 'Show', @department, class: 'btn btn-outline-dark m-2' %> |
<%= link_to 'Back', departments_path, class: 'btn btn-outline-secondary m-2' %>

<h1>Editing Department</h1>

<%= render 'form', department: @department %>

app/views/departments/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Departments</h1>
<%= link_to 'New Department', new_department_path, class: 'btn btn-outline-info m-2' %>

<table class="table">
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @departments.each do |department| %>
      <tr>
        <td><%= department.name %></td>
        <td><% department.images.each do |image| %>
          <%= image_tag(image.url, class: 'rounded m-2') %>
          <% end %>
        </td>
        <td class="d-flex justify-content-end">
          <%= link_to 'Show', department, class: 'btn btn-outline-dark m-2' %>
          <%= link_to 'Edit', edit_department_path(department), class: 'btn btn-outline-warning m-2' %>
          <%= link_to 'Destroy', department, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-outline-danger m-2' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/departments/new.html.erb
<%= link_to 'Back', departments_path, class: 'btn btn-outline-secondary m-2' %>

<h1>New Department</h1>

<%= render 'form', department: @department %>

app/views/departments/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_department_path(@department), class: 'btn btn-outline-warning m-2' %> |
<%= link_to 'Back', departments_path, class: 'btn btn-outline-secondary m-2' %>
<p>
  <strong>Name:</strong>
  <%= @department.name %>
</p>

<% @department.images.each do |image| %>
  <%= image_tag(image.url) %>
<% end %>

app/views/home/index.html.erb
<div>
  <p>WIP Spike exploring Carrierwave</p>
</div>

app/views/images/_form.html.erb
<%= form_with model: @image, url: images_path, local: true, html: { autocomplete: 'off' } do |f| %>

  <div class="form-group">
    <%= f.label :filename %>
    <%= f.file_field :filename, required: true %>
  </div>

  <%= f.submit 'Upload', class: 'btn btn-primary float-right' %>
<% end %>

app/views/images/edit.html.erb
<h1>Editing Image</h1>

<%= render 'form', image: @image %>

<%= link_to 'Show', @image, class: 'btn btn-outline-dark m-2' %> |
<%= link_to 'Back', images_path, class: 'btn btn-outline-secondary m-2' %>

app/views/images/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Images</h1>
<%= link_to 'New Image', new_image_path, class: 'btn btn-outline-info m-2' %>

<table class="table">
  <thead>
    <tr>
      <th>Filename</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @images.each do |image| %>
      <tr>
        <td><%= image_tag (image.filename.url), class: 'logo-img-lg m-2' %></td>
        <td class="d-flex justify-content-end">
          <%= link_to 'Show', image, class: 'btn btn-outline-dark m-2' %>
          <%= link_to 'Edit', edit_image_path(image), class: 'btn btn-outline-warning m-2' %>
          <%= link_to 'Destroy', image, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger m-2' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/images/new.html.erb
<h1>New Image</h1>

<%= render 'form', image: @image %>

<%= link_to 'Back', images_path, class: 'btn btn-outline-secondary m-2' %>

app/views/images/show.html.erb
<p id="notice"><%= notice %></p>

<%= image_tag (@image.filename.url), class: 'logo-img-lg m-2' %>
<span><%= @image.filename_identifier %></span>

<%= link_to 'Edit', edit_image_path(@image), class: 'btn btn-outline-warning m-2' %> |
<%= link_to 'Back', images_path, class: 'btn btn-outline-secondary m-2' %>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <%= link_to 'ImageUpload', home_path, class: 'nav-link' %>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNav">
    <ul class="navbar-nav">
      <li class="nav-item">
        <%= link_to 'Companies - Nested Attributes', companies_path, class: 'nav-link' %>
      </li>

      <li class="nav-item">
        <%= link_to 'Departments - MultiFile Upload', departments_path, class: 'nav-link' %>
      </li>
      <li class="nav-item">
        <%= link_to 'Images - Without Association', images_path, class: 'nav-link' %>
      </li>
    </ul>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ImageUploading</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render partial: 'layouts/navbar' %>
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>